### ISSUE TITLE
Topic example

### ISSUE THREAD

**Issue by FannyLee** [stjohnjohnson/mqtt-telegram#1]
Hi, I'm new in mqtt and telegram bot, and try this project recently. I have some problem, may I ask some question? 

```
mqtt:
//Specify your MQTT Broker's hostname or IP address here
    host: < my mqtt host >

telegram:
//Token to talk to Telegram
    token: < telegram bot token >

//Where to send events to
topics:
    sample/topic:
        - < chat id >
```

Is it right?
And when I want publish something to this topic, how to I write the topic? (ex: chat id = 111111111, and the the topic= sample/topic:111111111 ??)
Thank you :)
